(load "test.ss")
(load "ccc.ss")
(load "newvar.ss")


(display "while-1cons-expr-v")
(newvar-reset)
(test (while-1cons-expr-v (VAR "X") "A") 
      (cons () (VAR "X")))
(test (while-1cons-expr-v NIL "A") 
      (cons (list (SET (VAR "A0") NIL)) (VAR "A0")))
(test (while-1cons-expr-v (CST "truc") "A") 
      (cons (list (SET (VAR "A1") (CST "truc"))) (VAR "A1")))
(test (while-1cons-expr-v (HD (VAR "X")) "A") 
      (cons (list (SET (VAR "A2") (HD (VAR "X")))) (VAR "A2")))
(test (while-1cons-expr-v (HD (HD (VAR "X"))) "A") 
      (cons (list (SET (VAR "A3") (HD (VAR "X"))) 
                  (SET (VAR "A4") (HD (VAR "A3")))) (VAR "A4")))
(test (while-1cons-expr-v (HD (TL (HD NIL))) "A") 
      (cons (list (SET (VAR "A5") NIL) 
                  (SET (VAR "A6") (HD (VAR "A5"))) 
                  (SET (VAR "A7") (TL (VAR "A6"))) 
                  (SET (VAR "A8") (HD (VAR "A7")))) (VAR "A8")))
(test (while-1cons-expr-v (HD (TL (HD (VAR "X")))) "A") 
      (cons (list (SET (VAR "A9") (HD (VAR "X"))) 
                  (SET (VAR "A10") (TL (VAR "A9"))) 
                  (SET (VAR "A11") (HD (VAR "A10")))) (VAR "A11")))
(test (while-1cons-expr-v (CONS (TL (VAR "Y")) (HD (VAR "X"))) "A") 
      (cons (list (SET (VAR "A12") (TL (VAR "Y"))) 
                  (SET (VAR "A13") (HD (VAR "X"))) 
                  (SET (VAR "A14") (CONS (VAR "A12") (VAR "A13")))) (VAR "A14")))
(test (while-1cons-expr-v (EQ (TL (VAR "Y")) (HD (VAR "X"))) "A") 
      (cons (list (SET (VAR "A15") (TL (VAR "Y"))) 
                  (SET (VAR "A16") (HD (VAR "X"))) 
                  (SET (VAR "A17") (EQ (VAR "A15") (VAR "A16")))) (VAR "A17")))

(display "while-1cons-expr-se")
(newvar-reset)
(test (while-1cons-expr-se (VAR "X") "A") 
      (cons () (VAR "X")))
(test (while-1cons-expr-se NIL "A") 
      (cons () NIL))
(test (while-1cons-expr-se (CST "truc") "A") 
      (cons () (CST "truc")))
(test (while-1cons-expr-se (HD (VAR "X")) "A") 
      (cons () (HD (VAR "X"))))
(test (while-1cons-expr-se (HD (HD (VAR "X"))) "A") 
      (cons (list (SET (VAR "A0") (HD (VAR "X")))) 
                  (HD (VAR "A0"))))
(test (while-1cons-expr-se (HD (TL (HD NIL))) "A") 
      (cons (list (SET (VAR "A1") NIL) 
                  (SET (VAR "A2") (HD (VAR "A1"))) 
                  (SET (VAR "A3") (TL (VAR "A2")))) 
                  (HD (VAR "A3"))))
(test (while-1cons-expr-se (HD (TL (HD (VAR "X")))) "A") 
      (cons (list (SET (VAR "A4") (HD (VAR "X"))) 
                  (SET (VAR "A5") (TL (VAR "A4")))) 
                  (HD (VAR "A5"))))
(test (while-1cons-expr-se (CONS (TL (VAR "Y")) (HD (VAR "X"))) "A") 
      (cons (list (SET (VAR "A6") (TL (VAR "Y"))) 
                  (SET (VAR "A7") (HD (VAR "X")))) 
                  (CONS (VAR "A6") (VAR "A7"))))
(test (while-1cons-expr-se (EQ (TL (VAR "Y")) (HD (VAR "X"))) "A") 
      (cons (list (SET (VAR "A8") (TL (VAR "Y"))) 
                  (SET (VAR "A9") (HD (VAR "X")))) 
                  (EQ (VAR "A8") (VAR "A9"))))

(display "while-1cons-command")
(newvar-reset)
(test (while-1cons-command NOP "A") (list NOP))
(test (while-1cons-command (SET (VAR "X") (HD (HD (VAR "Z")))) "B") 
      (list (SET (VAR "B0") (HD (VAR "Z")))
            (SET (VAR "X") (HD (VAR "B0")))))
(test (while-1cons-command (SET (VAR "X") (VAR "Z")) "C")
      (list (SET (VAR "X") (VAR "Z"))))
(test (while-1cons-command (SET (VAR "X") NIL) "D")
      (list (SET (VAR "X") NIL)))

(newvar-reset)
(test (while-1cons-command (WHILE (EQ (HD (VAR "X")) (TL (VAR "Y"))) 
                                  (list (SET (VAR "X") (HD (HD (VAR "Z")))))) "E")
      (list (SET (VAR "E0") (HD (VAR "X")))
            (SET (VAR "E1") (TL (VAR "Y")))
            (SET (VAR "E2") (EQ (VAR "E0") (VAR "E1")))
            (WHILE (VAR "E2") (list (SET (VAR "E3") (HD (VAR "Z")))
                                    (SET (VAR "X") (HD (VAR "E3")))
                                    (SET (VAR "E0") (HD (VAR "X")))
                                    (SET (VAR "E1") (TL (VAR "Y")))
                                    (SET (VAR "E2") (EQ (VAR "E0") (VAR "E1")))
            ))))
(newvar-reset)
(test (while-1cons-command (IF (EQ (HD (VAR "X")) (TL (VAR "Y")))
                               (list (SET (VAR "X") (HD (HD (VAR "Z")))))
                               (list (SET (VAR "U") (HD (HD (VAR "V")))))) "E")
      (list (SET (VAR "E0") (HD (VAR "X")))
            (SET (VAR "E1") (TL (VAR "Y")))
            (SET (VAR "E2") (EQ (VAR "E0") (VAR "E1")))
            (IF (VAR "E2") 
                (list (SET (VAR "E3") (HD (VAR "Z")))
                      (SET (VAR "X") (HD (VAR "E3")))) 
                (list (SET (VAR "E4") (HD (VAR "V")))
                      (SET (VAR "U") (HD (VAR "E4")))
                      ))))
(newvar-reset)
(test (while-1cons-command (FOR (VAR "I") (list (SET (VAR "X") (HD (HD (VAR "Z")))))) "E") 
      (list (FOR (VAR "I") 
                 (list (SET (VAR "E0") (HD (VAR "Z")))
                      (SET (VAR "X") (HD (VAR "E0")))))))

(display "while-1cons-progr")
(newvar-reset)
(test (while-1cons-progr (PROGR (list (VAR "X")) 
                           (list (SET (VAR "Y") NIL) 
                                 (WHILE (VAR "X") 
                                        (list (SET (VAR "Y") (CONS (HD (VAR "X")) (VAR "Y")))
                                              (WHILE (VAR "X") 
                                                     (list (SET (VAR "Y") 
                                                                (CONS (HD (VAR "X")) (VAR "Y")))               
                                                           (SET (VAR "X") (TL (VAR "X")))))  
                                              (SET (VAR "X") (TL (VAR "X"))))) )
                           (list (VAR "Y")))
                         "A")
      (PROGR (list (VAR "X")) 
             (list (SET (VAR "Y") NIL) 
                   (WHILE (VAR "X") 
                          (list (SET (VAR "A0") (HD (VAR "X"))) 
                                (SET (VAR "Y") (CONS (VAR "A0") (VAR "Y"))) 
                                (WHILE (VAR "X") 
                                       (list (SET (VAR "A1") (HD (VAR "X"))) 
                                             (SET (VAR "Y") (CONS (VAR "A1") (VAR "Y"))) 
                                             (SET (VAR "X") (TL (VAR "X"))))) 
                                (SET (VAR "X") (TL (VAR "X")))))) 
             (list (VAR "Y"))))
(newvar-reset)
(test (while-1cons-progr (PROGR (list (VAR "X")) 
                           (list (SET (VAR "Y") NIL) 
                                 (WHILE (VAR "X") 
                                        (list (SET (VAR "Y") (CONS (HD (VAR "X")) (VAR "Y"))) 
                                              (SET (VAR "X") (TL (VAR "X"))))) )
                           (list (VAR "Y")))
                         "A") 
    (PROGR (list (VAR "X")) 
           (list (SET (VAR "Y") NIL) 
                 (WHILE (VAR "X") 
                        (list (SET (VAR "A0") (HD (VAR "X"))) 
                              (SET (VAR "Y") (CONS (VAR "A0") (VAR "Y"))) 
                              (SET (VAR "X") (TL (VAR "X")))))) 
           (list (VAR "Y"))))

(display "while-1cons")
(newvar-reset)
(test (while-1cons (PROGR (list (VAR "X")) 
                           (list (SET (VAR "Y") NIL) 
                                 (WHILE (VAR "X") 
                                        (list (SET (VAR "Y") (CONS (HD (VAR "X")) (VAR "Y"))) 
                                              (SET (VAR "X") (TL (VAR "X"))))) )
                           (list (VAR "Y")))
                         "A") 
    (PROGR (list (VAR "X")) 
           (list (SET (VAR "Y") NIL) 
                 (WHILE (VAR "X") 
                        (list (SET (VAR "A0") (HD (VAR "X"))) 
                              (SET (VAR "Y") (CONS (VAR "A0") (VAR "Y"))) 
                              (SET (VAR "X") (TL (VAR "X")))))) 
           (list (VAR "Y"))))
(newvar-reset)
(test (while-1cons (PROGR (list (VAR "X")) 
                           (list (SET (VAR "Y") NIL) 
                                 (WHILE (VAR "X") 
                                        (list (SET (VAR "Y") (CONS (HD (VAR "X")) (VAR "Y"))) 
                                              (SET (VAR "X") (TL (VAR "X"))))) )
                           (list (VAR "Y")))) 
    (PROGR (list (VAR "X")) 
           (list (SET (VAR "Y") NIL) 
                 (WHILE (VAR "X") 
                        (list (SET (VAR "Z0") (HD (VAR "X"))) 
                              (SET (VAR "Y") (CONS (VAR "Z0") (VAR "Y"))) 
                              (SET (VAR "X") (TL (VAR "X")))))) 
           (list (VAR "Y"))))
